name: Playwright Tests - By Atullya

# Triggers for the workflow
on:
  push:                  # Run the workflow on push events
    branches: ["main"]   # Only for the 'main' branch
  pull_request:          # Run the workflow on pull request events
    branches: ["main"]   # Only when PR targets the 'main' branch
  schedule:              # Schedule to run at 01:30 AM from Monday to Friday
    - cron: "30 1 * * 1-5"
  workflow_dispatch:     # Allows manual trigger from the GitHub UI

jobs:
  test:
    timeout-minutes: 60  # Maximum time allowed for the job to run (1 hour)
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - uses: actions/checkout@v4
        # Checks out your repository's code into the workflow

      - uses: actions/setup-node@v4
        # Sets up Node.js environment (corrected spelling from 'steup' to 'setup')

      - name: Install dependencies
        run: npm ci
        # Installs Node.js dependencies based on your package-lock.json (clean install)

      - name: Run Playwright test
        run: npx playwright test
        # Executes Playwright tests

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
          # Uploads the Playwright test report even if tests fail
          # Stores it as an artifact named 'playwright-report'
          # Keeps the artifact for 30 days
